config/routes.rb
GMapEdit::Application.routes.draw do

  devise_for :users

  get "map/index"
  get "map/menu"
  get "map/kml", :as => "kml"


  resources :polygons
  resources :polylines
  resources :points

  root :to => "home#index"
end

app/models/point.rb
class Point < ActiveRecord::Base

  validates_presence_of :data

  belongs_to :user


end

app/models/polygon.rb
class Polygon < ActiveRecord::Base

  validates_presence_of :data

  belongs_to :user
  

end

app/models/polyline.rb
class Polyline < ActiveRecord::Base

  validates_presence_of :data

  belongs_to :user
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :polygons
  has_many :polylines
  has_many :points


  def to_s
    email
  end

end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController

  def index
    if current_user
      redirect_to map_index_path 
    end
  end

end

app/controllers/map_controller.rb
# -*- encoding : utf-8 -*-
class MapController < ApplicationController
  layout 'map'
  before_filter :authenticate_user!

  def index
  end

  def menu
    
  end

  def kml
    @points = current_user.points.all
    @polygons = current_user.polygons.all
    @polylines = current_user.polylines.all
    output = render_to_string "map/kml", :layout => false
    # raise output
    send_data output, :filename => "#{current_user.id}_mapa.kml"
  end

end

app/controllers/points_controller.rb
class PointsController < ApplicationController


  def index
    respond_to do |format|
      format.js { render :json => current_user.points.to_json(:only => [ :id, :name, :description, :color, :data ]) }
    end
  end

  def show
    respond_to do |format|
      format.js { render :json => current_user.points.find(params[:id]).to_json(:only => [ :id, :name, :description, :color, :data ]) }
    end
  end


  def destroy
    point = current_user.points.find(params[:id])
    if point.destroy
      response = { :status => 'success'}
    else
      response = { :status => 'failed' }
    end
    respond_to do |format|
      format.js { render :json => response }
    end

  end


  def update
    point = current_user.points.find(params[:id])
    point.update_attributes(params[:point])

    if point.save
      response = { :status => 'success'}
    else
      response = { :status => 'failed' }
    end
    respond_to do |format|
      format.js { render :json => response }
    end

  end

  def new
    @point = Point.new
    respond_to do |format|
      format.js
    end
  end

  def edit
    @point = current_user.points.find(params[:id])
    
  end

  def create
    point = current_user.points.create(params[:point])
    if point.save
      response = { :status => 'success', :id => point.id }
    else
      response = { :status => 'failed' }
    end
    respond_to do |format|
      format.js { render :json => response }
    end
  end


end

app/controllers/polygons_controller.rb
class PolygonsController < ApplicationController

  def index
    respond_to do |format|
      format.js { render :json => current_user.polygons.to_json(:only => [ :id, :name, :description, :color, :data ]) }
    end
  end

  def show
    respond_to do |format|
      format.js { render :json => current_user.polygons.find(params[:id]).to_json(:only => [ :id, :name, :description, :color, :data ]) }
    end
  end


  def destroy
    polygon = current_user.polygons.find(params[:id])
    if polygon.destroy
      response = { :status => 'success'}
    else
      response = { :status => 'failed' }    
    end
    respond_to do |format|
      format.js { render :json => response }
    end

  end


  def update
    polygon = current_user.polygons.find(params[:id])
    polygon.update_attributes(params[:polygon])

    if polygon.save
      response = { :status => 'success'}
    else
      response = { :status => 'failed' }
    end
    respond_to do |format|
      format.js { render :json => response }
    end

  end

  def new
    @polygon = Polygon.new
    respond_to do |format|
      format.js
    end
  end

  def edit
    @polygon = current_user.polygons.find(params[:id])
  end

  def create
    polygon = current_user.polygons.create(params[:polygon])
    if polygon.save
      response = { :status => 'success', :id => polygon.id }
    else
      response = { :status => 'failed' }
    end
    respond_to do |format|
      format.js { render :json => response }
    end
  end

end

app/controllers/polylines_controller.rb
class PolylinesController < ApplicationController


  def index
    respond_to do |format|
      format.js { render :json => current_user.polylines.to_json(:only => [ :id, :name, :description, :color, :data ]) }
    end
  end

  def show
    respond_to do |format|
      format.js { render :json => current_user.polylines.find(params[:id]).to_json(:only => [ :id, :name, :description, :color, :data ]) }
    end
  end


  def destroy
    polyline = current_user.polylines.find(params[:id])
    if polyline.destroy
      response = { :status => 'success'}
    else
      response = { :status => 'failed' }
    end
    respond_to do |format|
      format.js { render :json => response }
    end

  end


  def update
    polyline = current_user.polylines.find(params[:id])
    polyline.update_attributes(params[:polyline])

    if polyline.save
      response = { :status => 'success'}
    else
      response = { :status => 'failed' }
    end
    respond_to do |format|
      format.js { render :json => response }
    end

  end

  def new
    @polyline = Polyline.new
    respond_to do |format|
      format.js
    end
  end

  def edit
    @polyline = current_user.polylines.find(params[:id])
  end

  def create
    polyline = current_user.polylines.create(params[:polyline])
    if polyline.save
      response = { :status => 'success', :id => polyline.id }
    else
      response = { :status => 'failed' }
    end
    respond_to do |format|
      format.js { render :json => response }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_helper.rb
module MapHelper

  def p(latlng)
    temp = latlng.split(',')
    "#{temp[1]},#{temp[0]},0"
  end

  def p_multi(data)
    temp = data.split('|')
    result = ''
    temp.each do |t|
      result += "\n#{p(t)}"
    end
    "#{result}\n"
  end

  def get_surface(data)
    latitiude = []
    longitude = []
    data.split('|').each do |e|
      lat, lng = e.split(',')
      latitiude.push(lat.to_f)
      longitude.push(lng.to_f)
    end

    earth_radius = 6371009 # srednica ziemi w metrach
    lat_dist = Math::PI * earth_radius / 180.0
    y = latitiude.map{|l| l * lat_dist}
    x = longitude.map.with_index{|l,i| l * lat_dist * Math.cos(latitiude[i]*Math::PI/180)}
    area = 0.0
    for i in -1..(x.count-2)
      area += x[i] * (y[i+1] - y[i-1])
    end
    (area/2.0).abs    
  end

end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/polygons_helper.rb
module PolygonsHelper
end

app/helpers/polylines_helper.rb
module PolylinesHelper
end

app/views/home/index.html.haml
%ul.links
  %li
    = link_to "Zaloguj się", new_user_session_path
  %li
    %br lub  
  %li
    = link_to "zarejestruj się", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :charset => 'utf-8' }
    %title GMapEdit
    = stylesheet_link_tag "reset", "application"
    = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"
    = javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false"
    = javascript_include_tag "cs/underscore", "cs/gmapedit", "cs/polyline.gmapedit", "cs/polygon.gmapedit", "cs/application"
    = csrf_meta_tag
    %body
      #login
        %h1 GMapEdit

        - if alert
          .flash.alert= alert
        - if notice
          .flash.alert= notice
        = yield
      

app/views/layouts/map.html.haml
!!!
%html
  %head
    %meta{ :charset => 'utf-8' }
    %title GMapEdit
    = stylesheet_link_tag "reset", "menu",  "application"
    = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"
    = javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false&libraries=geometry"
    = javascript_include_tag "rails", "json2"   
    = javascript_include_tag "cs/underscore", "cs/gmapedit", "cs/polygon.gmapedit", "cs/polyline.gmapedit", "cs/point.gmapedit", "cs/application"
    = csrf_meta_tag
    %body
      = yield

app/views/map/_new_object_list.html.haml
%a.drop{:href => '#'} Nowy obiekt
.dropdown_1column.align_right
  .col_1
    %ul.simple
      %li= link_to 'Nowa powierzchnia', new_polygon_path, :id => 'new_polygon_link'
      %li= link_to 'Nowa trasa', new_polyline_path, :id => 'new_polyline_link'
      %li= link_to 'Nowy punkt', new_point_path, :id => 'new_point_link'

app/views/map/index.html.haml
#container
  .overmap
    #box
    #top
      %ul#menu
        %li
          %a.drop{:href => '#'}
            O aplikacji
          .dropdown_5columns
            .col_5
              To jest aplikacja pracy inżynierskiej
        %li.menu_left
          %a.drop{:href => '#'} Użytkownik
          .dropdown_1column
            .col_1
              %ul.simple
                %li
                  = link_to "Wyloguj (#{current_user})", destroy_user_session_path
        %li.menu_right#form_menu
          = render "new_object_list"
        %li.menu_right
          = link_to 'Zapisz do KML', kml_path, {:target => :blank}

    .container
      - if alert
        .flash.alert= alert
      - if notice
        .flash.notice= notice
  #map

app/views/map/menu.js.erb
$('#form_menu').html("<%= escape_javascript( render "new_object_list" )%>");

app/views/points/_point_form.html.haml
%a.drop{:href => '#'}
  - if @point.name.blank?
    Nowy punkt
  - else
    = "#{@point.name} (punkt)"
.dropdown_3columns.align_right
  .col_3
    = semantic_form_for  @point do |f|
      = f.inputs do
        = f.input :name
        = f.input :description
        = f.input :data, :as => :hidden
      = f.buttons do
        = f.commit_button :label => 'Zapisz '
        %li.align_right
          = link_to 'Anuluj', nil, :id => 'cancel'
        %li.align_right
          = link_to 'Usuń', @point, { :id => 'delete'} if @point.id

app/views/points/edit.js.erb
$('#form_menu').html("<%= escape_javascript( render "point_form" )%>");

app/views/points/new.js.erb
$('#form_menu').html("<%= escape_javascript( render "point_form" )%>");

app/views/polygons/_polygon_form.html.haml
%a.drop{:href => '#'}
  - if @polygon.name.blank?
    Nowa powierzchnia
  - else
    = "#{@polygon.name} (powierzchnia)"
.dropdown_3columns.align_right
  .col_3
    = semantic_form_for  @polygon do |f|
      = f.inputs do
        = f.input :name
        = f.input :description
        = f.input :data, :as => :hidden
        = f.input :surface, :as => :hidden
        %li
          #surface
            %b Powierzchnia:
            0 km2
      = f.buttons do
        = f.commit_button :label => 'Zapisz '
        %li.align_right
          = link_to 'Anuluj', nil, :id => 'cancel'
        %li.align_right
          = link_to 'Usuń', @polygon, { :id => 'delete'} if @polygon.id

app/views/polygons/edit.js.erb
$('#form_menu').html("<%= escape_javascript( render "polygon_form" )%>");

app/views/polygons/new.js.erb
$('#form_menu').html("<%= escape_javascript( render "polygon_form" )%>");

app/views/polylines/_polyline_form.html.haml
%a.drop{:href => '#'}
  - if @polyline.name.blank?
    Nowa trasa
  - else
    = "#{@polyline.name} (trasa)"
.dropdown_3columns.align_right
  .col_3
    = semantic_form_for  @polyline do |f|
      = f.inputs do
        = f.input :name
        = f.input :description
        = f.input :data, :as => :hidden
        = f.input :length, :as => :hidden
        %li
          #length
            %b Długość:
            0 km
      = f.buttons do
        = f.commit_button :label => 'Zapisz '
        %li.align_right
          = link_to 'Anuluj', nil, :id => 'cancel'
        %li.align_right
          = link_to 'Usuń', @polyline, { :id => 'delete'} if @polyline.id

app/views/polylines/edit.js.erb
$('#form_menu').html("<%= escape_javascript( render "polyline_form" )%>");

app/views/polylines/new.js.erb
$('#form_menu').html("<%= escape_javascript( render "polyline_form" )%>");